question_data = [{"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The ARM computer chip was originally developed by Acorn Computers.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The &#039;Raspberry Pi&#039; series of single-board computers were created in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
